# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T16:57:25+00:00



import argparse
import json
import os
from datetime import date, datetime
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity
from pydantic import conint, constr

from models import (
    AudioDescribed,
    Authority,
    Availability6,
    Availability7,
    Availability8,
    AvailabilityEntityType,
    AvailabilityType1,
    ChildrenOf,
    DescendantsOf,
    Duration,
    Embargoed1,
    EntityType,
    ErrorModel,
    Format1,
    Genre1,
    GroupType,
    HasExternalId,
    Id1,
    IdType,
    ImageType,
    InitialLetterStrict,
    Item1,
    ItemType,
    MasterBrand3,
    MediaSet1,
    MediaType1,
    Mid1,
    Mixin1,
    Mixin2,
    Mixin3,
    Mixin4,
    Mixin5,
    Mixin6,
    Mixin7,
    Nitro,
    PartnerId,
    PartnerPid,
    PaymentType,
    PaymentType1,
    Pid1,
    PromotedBy1,
    PromotedFor1,
    ServiceMasterBrand,
    ServiceType,
    Sid1,
    Signed,
    Sort1,
    Sort3,
    Sort5,
    Sort7,
    Sort9,
    Sort11,
    Sort13,
    Sort15,
    SortDirection1,
    SortDirection5,
    SortDirection7,
    SortDirection9,
    SortDirection11,
    SortDirection13,
    Status1,
    Territory,
    Tleo,
    Version4,
)

app = MCPProxy(
    contact={
        'email': 'nitro@bbc.co.uk',
        'name': 'Open Nitro Project',
        'url': 'http://developer.bbc.co.uk/',
    },
    description="BBC Nitro is the BBC's application programming interface (API) for BBC Programmes Metadata.",
    license={
        'name': 'Nitro Public License',
        'url': 'https://github.com/Mermade/bbcparse/wiki/Nitro-Public-License',
    },
    termsOfService='http://www.bbc.co.uk/terms/',
    title='BBC Nitro API',
    version='1.0.0',
    servers=[{'url': 'https://programmes.api.bbc.com'}],
)


@app.get(
    '/#-datamodel-code-generator-#-root-#-special-#',
    description=""" Get API definition """,
    tags=['api_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get_a_p_i():
    """
    Get API definition
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/availabilities',
    description=""" Discover details of on-demand availability for programmes and their versions """,
    tags=['programme_metadata', 'editorial_version_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_availability(
    sort: Optional[Sort1] = None,
    sort_direction: Optional[SortDirection1] = None,
    availability: Optional[Availability6] = None,
    descendants_of: Optional[DescendantsOf] = None,
    media_set: Optional[MediaSet1] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    territory: Optional[Territory] = None,
    debug: Optional[bool] = None,
):
    """
    Discover details of on-demand availability for programmes and their versions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/broadcasts',
    description=""" Fetch metadata about linear Broadcasts and Services, allowing the generation of Television and Radio schedules and other datasets for broadcast items. Use /schedules instead of this feed as it is more efficient. Broadcasts will be deprecated in the future. """,
    tags=['programme_metadata', 'broadcast_schedule_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_broadcasts(
    sort: Optional[Sort3] = None,
    sort_direction: Optional[SortDirection1] = None,
    mixin: Optional[Mixin1] = None,
    authority: Optional[Authority] = None,
    descendants_of: Optional[DescendantsOf] = None,
    end_from: Optional[datetime] = None,
    end_to: Optional[datetime] = None,
    format: Optional[Format1] = None,
    genre: Optional[Genre1] = None,
    id: Optional[Id1] = None,
    item: Optional[Item1] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    people: Optional[str] = None,
    pid: Optional[Pid1] = None,
    q: Optional[str] = None,
    schedule_day: Optional[date] = None,
    schedule_day_from: Optional[date] = None,
    schedule_day_to: Optional[date] = None,
    service_master_brand: Optional[ServiceMasterBrand] = None,
    sid: Optional[Sid1] = None,
    start_from: Optional[datetime] = None,
    start_to: Optional[datetime] = None,
    version: Optional[Version4] = None,
):
    """
    Build schedules and find metadata for TV and radio broadcasts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/groups',
    description=""" Long-lived curated collections of programmes and more, including Collections, Seasons, Franchises and Galleries """,
    tags=['curated_group_management', 'programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_groups(
    sort: Optional[Sort5] = None,
    sort_direction: Optional[SortDirection5] = None,
    mixin: Optional[Mixin2] = None,
    for_descendants_of: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    for_programme: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    group: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    group_type: Optional[GroupType] = None,
    member: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    pid: Optional[Pid1] = None,
    q: Optional[str] = None,
    embargoed: Optional[Embargoed1] = None,
):
    """
    Find metadata for curated groups: seasons, collections, galleries or franchises
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/images',
    description=""" Find metadata for images, particularly those in galleries """,
    tags=['image_metadata_management', 'programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_images(
    sort: Optional[Sort7] = None,
    sort_direction: Optional[SortDirection7] = None,
    group: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    image_type: Optional[ImageType] = None,
    is_alternate_image_for: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    is_image_for: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    pid: Optional[Pid1] = None,
    q: Optional[str] = None,
    embargoed: Optional[Embargoed1] = None,
):
    """
    Find metadata for images
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/items',
    description=""" Look inside programmes to find segments: chapters, tracks and more """,
    tags=['programme_metadata', 'curated_group_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_items(
    sort: Optional[Sort9] = None,
    sort_direction: Optional[SortDirection9] = None,
    mixin: Optional[Mixin3] = None,
    authority: Optional[str] = None,
    id: Optional[Id1] = None,
    id_type: Optional[str] = None,
    item_type: Optional[ItemType] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    people: Optional[str] = None,
    pid: Optional[Pid1] = None,
    programme: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    q: Optional[str] = None,
    segment_event: Optional[str] = None,
):
    """
    Look inside programmes to find segments: chapters, tracks and more
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/master_brands',
    description=""" List all Master Brands """,
    tags=['programme_metadata', 'curated_group_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_masterbrands(
    sort: Optional[Sort11] = None,
    sort_direction: Optional[SortDirection11] = None,
    mixin: Optional[Mixin4] = None,
    mid: Optional[Mid1] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    q: Optional[str] = None,
):
    """
    List all Master Brands
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/people',
    description=""" The People feed allows you to search for the people and groups that contribute to programmes. This is the starting point for cast and crew credits, as well as finding contributors using external IDs (such as Wikipedia URLs) """,
    tags=['programme_metadata', 'individuals_metadata_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_people(
    authority: Optional[str] = None,
    has_external_id: Optional[HasExternalId] = None,
    id: Optional[Id1] = None,
    id_type: Optional[str] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    pid: Optional[Pid1] = None,
    programme: Optional[str] = None,
    q: Optional[str] = None,
):
    """
    Find the people behind and in programmes: cast, crew, guests and more
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/pips',
    description=""" Look inside pips entities """,
    tags=['programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_pips(
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    q: Optional[str] = None,
):
    """
    Look inside pips entities
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/programme_details',
    description=""" Exposes programme information for a single pid """,
    tags=['programme_metadata', 'api_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_programme_details(
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_pid: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    pid: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
):
    """
    Exposes programme information for a single pid
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/programmes',
    description=""" Fetch metadata about Programmes (brands, series, episodes, clips). By applying different filter restrictions this feed can be used in many ways, for example to retrieve all series belonging to a brand, all the episodes and/or clips for a specific series, or any TLEO objects for a masterbrand. Other filters permit restricting to specific formats and/or genres, and you can request specific versions (for example Signed or Audio-Described). Parameters may be combined in any way suitable for your application. """,
    tags=['programme_metadata', 'curated_group_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_programmes(
    sort: Optional[Sort13] = None,
    sort_direction: Optional[SortDirection13] = None,
    mixin: Optional[Mixin5] = None,
    audio_described: Optional[AudioDescribed] = None,
    availability: Optional[Availability7] = None,
    availability_entity_type: Optional[AvailabilityEntityType] = None,
    availability_from: Optional[datetime] = None,
    availability_type: Optional[AvailabilityType1] = None,
    children_of: Optional[ChildrenOf] = None,
    descendants_of: Optional[DescendantsOf] = None,
    duration: Optional[Duration] = None,
    entity_type: Optional[EntityType] = None,
    format: Optional[Format1] = None,
    genre: Optional[Genre1] = None,
    group: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    initial_letter: Optional[constr(min_length=1, max_length=1)] = None,
    initial_letter_end: Optional[constr(min_length=1, max_length=1)] = None,
    initial_letter_start: Optional[constr(min_length=1, max_length=1)] = None,
    initial_letter_strict: Optional[InitialLetterStrict] = None,
    item: Optional[Item1] = None,
    master_brand: Optional[MasterBrand3] = None,
    media_set: Optional[str] = None,
    media_type: Optional[MediaType1] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    payment_type: Optional[PaymentType] = None,
    people: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    pid: Optional[Pid1] = None,
    promoted_for: Optional[str] = None,
    q: Optional[str] = None,
    signed: Optional[Signed] = None,
    tag_name: Optional[str] = None,
    tag_scheme: Optional[str] = None,
    tleo: Optional[Tleo] = None,
    version: Optional[Version4] = None,
    embargoed: Optional[Embargoed1] = None,
):
    """
    Start here for programmes metadata: Brands, Series, Episodes and Clips
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/promotions',
    description=""" Details of short-term editorially curated "promotions", for instance those programmes featured on iPlayer today """,
    tags=['content_promotion_management', 'programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_promotions(
    mixin: Optional[Mixin6] = None,
    context: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    pid: Optional[Pid1] = None,
    promoted_by: Optional[PromotedBy1] = None,
    promoted_for: Optional[PromotedFor1] = None,
    q: Optional[str] = None,
    status: Optional[Status1] = None,
):
    """
    Discover metadata for content promotions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/schedules',
    description=""" Dates, Times, Schedules: when and where are programmes being shown? """,
    tags=['broadcast_schedule_management', 'programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_schedules(
    sort: Optional[Sort15] = None,
    sort_direction: Optional[SortDirection13] = None,
    mixin: Optional[Mixin7] = None,
    authority: Optional[Authority] = None,
    descendants_of: Optional[DescendantsOf] = None,
    end_from: Optional[datetime] = None,
    end_to: Optional[datetime] = None,
    format: Optional[Format1] = None,
    genre: Optional[Genre1] = None,
    group: Optional[
        constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)
    ] = None,
    id: Optional[Id1] = None,
    id_type: Optional[IdType] = None,
    item: Optional[Item1] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    people: Optional[str] = None,
    pid: Optional[Pid1] = None,
    q: Optional[str] = None,
    repeat: Optional[bool] = None,
    schedule_day: Optional[date] = None,
    schedule_day_from: Optional[date] = None,
    schedule_day_to: Optional[date] = None,
    service_master_brand: Optional[ServiceMasterBrand] = None,
    sid: Optional[Sid1] = None,
    start_from: Optional[datetime] = None,
    start_to: Optional[datetime] = None,
    version: Optional[Version4] = None,
):
    """
    Build schedules and find metadata for TV and radio broadcasts and webcasts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/schema',
    description=""" Get Schema definition """,
    tags=['api_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get_x_s_d():
    """
    Get Schema definition
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/services',
    description=""" The services feed exposes the linear broadcast "services" from PIPs. These are the actual services which broadcast programmes (eg bbc_one_oxford is the service for BBC One in Oxford). """,
    tags=['linear_service_management', 'broadcast_schedule_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_services(
    end_from: Optional[datetime] = None,
    end_to: Optional[datetime] = None,
    mid: Optional[Mid1] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    q: Optional[str] = None,
    service_type: Optional[ServiceType] = None,
    sid: Optional[Sid1] = None,
    start_from: Optional[datetime] = None,
    start_to: Optional[datetime] = None,
):
    """
    Information about the linear services used for broadcast transmissions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/brands/{pid}',
    description=""" Get raw brand """,
    tags=['programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_brand(pid: str):
    """
    Get raw brand
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/brands/{pid}/franchises/',
    description=""" Get raw brand franchises """,
    tags=['programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_brand_franchises(pid: str):
    """
    Get raw brand franchise
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/episodes/{pid}',
    description=""" Get raw episode """,
    tags=['programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_episode(pid: str):
    """
    Get raw episode
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/episodes/{pid}/ancestors/',
    description=""" Get raw ancestors """,
    tags=['programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_ancestors(pid: str):
    """
    Get raw ancestors
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/episodes/{pid}/formats/',
    description=""" Get raw formats """,
    tags=['programme_metadata', 'editorial_version_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_formats(pid: str):
    """
    Get raw formats
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/episodes/{pid}/genre_groups/',
    description=""" Get raw genre groups """,
    tags=['programme_metadata', 'curated_group_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_genre_groups(pid: str):
    """
    Get raw genre groups
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/images/{pid}',
    description=""" Get raw image """,
    tags=['image_metadata_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_image(pid: str):
    """
    Get raw image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/master_brands/{mbid}',
    description=""" Get raw masterbrand """,
    tags=['programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_masterbrand(mbid: str):
    """
    Get raw masterbrand
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/promotions/{pid}',
    description=""" Get raw promotion """,
    tags=['content_promotion_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get__raw_promotion(pid: str):
    """
    Get raw promotion
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/versions',
    description=""" The versions feed exposes editorial "Versions" of programmes. These are concepts used to capture different presentations of an overall programme: for example, versions of a programme may include one with sign language, one with audio description, one edited for content and more. Versions are also important to understand for broadcasts: a linear broadcast or an ondemand is always of a specific version, not merely of a programme. """,
    tags=['editorial_version_management', 'programme_metadata'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def list_versions(
    availability: Optional[Availability8] = None,
    descendants_of: Optional[DescendantsOf] = None,
    media_set: Optional[MediaSet1] = None,
    page: Optional[conint(ge=1)] = 1,
    page_size: Optional[conint(le=300)] = 10,
    partner_id: Optional[PartnerId] = None,
    partner_pid: Optional[PartnerPid] = None,
    payment_type: Optional[PaymentType1] = None,
    pid: Optional[Pid1] = None,
    embargoed: Optional[Embargoed1] = None,
):
    """
    Metadata on editorial programme versions: original, signed, audio-described, etc
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
