# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T16:57:25+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Detail(BaseModel):
    errorcode: Optional[str] = None


class Fault(BaseModel):
    detail: Optional[Detail] = None
    faultString: Optional[str] = None


class ErrorModel(BaseModel):
    fault: Optional[Fault] = None


class ActualStart(RootModel[datetime]):
    root: datetime


class AdvertisingAllowed(RootModel[constr(pattern=r'[a-z0-9_]+')]):
    root: constr(pattern=r'[a-z0-9_]+')


class FilterItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    name: str


class FilterItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    filter: Optional[List[FilterItem1]] = None
    name: str


class AffectedBy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filter: Optional[List[FilterItem]] = None


class AlternateImageItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    template_url: str
    type: Optional[str] = None


class AlternateImages1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alternate_image: Optional[List[AlternateImageItem1]] = None


class AlternateImageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alternate_images: AlternateImages1
    href: Optional[str] = None
    template_url: str
    type: Optional[str] = None


class AlternateImages(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alternate_image: Optional[List[AlternateImageItem]] = None


class AlternateImagesMixin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alternate_images: AlternateImages


class VersionTypeItem3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Optional[datetime] = None
    id: Optional[str] = None
    start: Optional[datetime] = None


class VersionTypeItem2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Optional[datetime] = None
    id: Optional[str] = None
    start: Optional[datetime] = None
    version_type: List[VersionTypeItem3] = Field(..., min_length=1)


class VersionTypes1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_type: List[VersionTypeItem2] = Field(..., min_length=1)


class AvailabilityType(Enum):
    ondemand = 'ondemand'
    simulcast = 'simulcast'
    webcast = 'webcast'


class MediaSetItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')


class MediaSets1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_set: List[MediaSetItem1] = Field(..., min_length=1)


class MediaSetItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    media_sets: Optional[MediaSets1] = None


class MediaSets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_set: List[MediaSetItem] = Field(..., min_length=1)


class AvailableMediaSets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_sets: Optional[MediaSets] = None


class Type(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Optional[List[str]] = None


class Territories1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    territory: Optional[List[str]] = None


class MediaSetItem3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actual_start: Optional[datetime] = None
    name: str
    territories: Optional[Territories1] = None


class MediaSets3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_set: List[MediaSetItem3] = Field(..., min_length=1)


class Territories(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_sets: Optional[MediaSets3] = None
    territory: Optional[List[str]] = None


class MediaSetItem2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actual_start: Optional[datetime] = None
    name: str
    territories: Optional[Territories] = None


class MediaSets2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_set: List[MediaSetItem2] = Field(..., min_length=1)


class AvailableVersionsMediaSets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_sets: Optional[MediaSets2] = None


class Caption(RootModel[str]):
    root: str


class CatalogueNumber(RootModel[constr(min_length=1, max_length=32)]):
    root: constr(min_length=1, max_length=32)


class Code(RootModel[str]):
    root: str


class CompetitionWarning(RootModel[bool]):
    root: bool


class ContainersTitle(RootModel[str]):
    root: str


class CreditRole(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    id: Optional[str] = None


class Name1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family: Optional[str] = None
    given: Optional[str] = None
    presentation: Optional[str] = None
    title: Optional[str] = None


class Name(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family: Optional[str] = None
    given: Optional[str] = None
    name: Name1
    presentation: Optional[str] = None
    title: Optional[str] = None


class ContributionsMixinContributorName(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name


class Name3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family: Optional[str] = None
    given: Optional[str] = None
    lang: Optional[str] = None
    presentation: Optional[str] = None
    title: Optional[str] = None


class Name2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family: Optional[str] = None
    given: Optional[str] = None
    lang: Optional[str] = None
    name: Name3
    presentation: Optional[str] = None
    title: Optional[str] = None


class ContributorName(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name2


class ContributorTo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    result_type: str


class CreditsTime(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    squeeze_end: Optional[datetime] = None
    squeeze_start: Optional[datetime] = None


class DateRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Optional[datetime] = None
    start: Optional[datetime] = None


class Datum(RootModel[str]):
    root: str


class DependencyOn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filter: Optional[str] = None
    value: Optional[str] = None


class Deprecated(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deprecated_since: constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')
    name: str
    replaced_by: Optional[str] = None
    replacement_type: Optional[str] = None
    type: str


class DeprecationAttributes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deprecated: bool
    deprecated_since: constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')
    replaced_by: str


class Deprecations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deprecated: Optional[List[Deprecated]] = None


class Description(RootModel[str]):
    root: str


class Dimensions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    height: Optional[int] = None
    width: Optional[int] = None


class Disambiguation(RootModel[str]):
    root: str


class Embargoed(Enum):
    true = 'true'
    false = 'false'


class End(RootModel[datetime]):
    root: datetime


class EndTime(RootModel[datetime]):
    root: datetime


class ErrorName(RootModel[str]):
    root: str


class ExpectedChildCount(RootModel[int]):
    root: int


class Expr(RootModel[str]):
    root: str


class FocusPoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: Optional[int] = None
    y: Optional[int] = None


class ForProgramme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None


class ForProgrammes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    for_programme: Optional[List[ForProgramme]] = None


class Format(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    format_id: Optional[str] = None


class FormatString(RootModel[str]):
    root: str


class Genre(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    id: Optional[str] = None
    type: Optional[str] = None


class Genres(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    genre: Optional[List[Genre]] = None


class GenreGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    genres: Genres
    id: Optional[str] = None
    type: Optional[str] = None


class HasGuidance(RootModel[bool]):
    root: bool


class Id(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    authority: Optional[str] = None
    type: Optional[str] = None


class Identifier(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    authority: Optional[str] = None
    type: Optional[str] = None


class Identifiers(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: List[Identifier] = Field(..., min_length=1)


class Ids(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: List[Id] = Field(..., min_length=1)


class InheritedFrom(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    result_type: Optional[str] = None


class Image4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    inherited_from: Optional[InheritedFrom] = None
    template_url: str
    type: Optional[str] = None


class Images1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image: Optional[Image4] = None


class Image3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    images: Images1
    inherited_from: Optional[InheritedFrom] = None
    template_url: str
    type: Optional[str] = None


class Images(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image: Optional[Image3] = None


class ImagesMixin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    images: Images


class IsAudioDescribed(RootModel[bool]):
    root: bool


class IsBlanked(RootModel[bool]):
    root: bool


class IsConcrete(RootModel[bool]):
    root: bool


class IsCritical(RootModel[bool]):
    root: bool


class IsDownloadable(RootModel[bool]):
    root: bool


class IsEmbeddable(RootModel[bool]):
    root: bool


class IsExternal(RootModel[bool]):
    root: bool


class IsRepeat(RootModel[bool]):
    root: bool


class IsSigned(RootModel[bool]):
    root: bool


class IsSimulcast(RootModel[bool]):
    root: bool


class IsStacked(RootModel[bool]):
    root: bool


class IsStreamable(RootModel[bool]):
    root: bool


class Long(RootModel[str]):
    root: str


class MasterBrandDateRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Optional[datetime] = None
    start: Optional[datetime] = None


class MediaAvailabilityTime(RootModel[DateRange]):
    root: DateRange


class MediaSet(RootModel[str]):
    root: str


class MediaType(Enum):
    Video = 'Video'
    Audio = 'Audio'


class Medium(RootModel[str]):
    root: str


class Message(RootModel[str]):
    root: str


class Mid(RootModel[str]):
    root: str


class MusicCode(RootModel[constr(min_length=1, max_length=8)]):
    root: constr(min_length=1, max_length=8)


class NameModel(RootModel[str]):
    model_config = ConfigDict(
        extra='forbid',
    )
    root: str


class Next(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str


class Pid(RootModel[constr(pattern=r'([a-z0-9\.\-]+|.*PID.*)')]):
    root: constr(pattern=r'([a-z0-9\.\-]+|.*PID.*)')


class PidReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    pid: Pid
    position: Optional[int] = None
    result_type: str


class PlayedIn1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    result_type: Optional[str] = None


class PlayedIn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    played_in: Optional[PlayedIn1] = None
    result_type: Optional[str] = None


class PlayedInLinks(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    played_in: Optional[PlayedIn] = None


class Position(RootModel[int]):
    root: int


class PresentationTitle(RootModel[str]):
    root: str


class Previous(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str


class Priority(RootModel[int]):
    root: int


class ProgrammeFormats(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    format: List[Format] = Field(..., min_length=1)


class ProgrammeType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: str


class FilterItem2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str


class MixinItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str


class MixinItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filter: Optional[List[FilterItem2]] = None
    mixin: Optional[List[MixinItem1]] = None
    name: str


class Prohibits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filter: Optional[List[FilterItem2]] = None
    mixin: Optional[List[MixinItem]] = None


class PromotedBy(RootModel[str]):
    root: str


class PromotedFor(RootModel[str]):
    root: str


class PromotionOf(RootModel[PidReference]):
    root: PidReference


class PublicationRights(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    context: Optional[str] = None
    platform: Optional[str] = None
    territory: Optional[str] = None
    transport: Optional[str] = None


class Publisher(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class RecordLabel(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class RecordingDate(RootModel[constr(min_length=4, max_length=10)]):
    root: constr(min_length=4, max_length=10)


class ReferenceAttributes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    result_type: str


class Region(RootModel[str]):
    root: str


class Availability1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Optional[datetime] = None
    start: Optional[datetime] = None


class ReleaseDateGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    release_date: Optional[constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')] = None
    release_year: Optional[constr(pattern=r'[0-9]{4}')] = None
    release_year_month: Optional[constr(pattern=r'[0-9]{4}-[0-9]{2}')] = None


class ReleaseStatusType(Enum):
    alpha = 'alpha'
    beta = 'beta'
    supported = 'supported'
    deprecated = 'deprecated'


class ReleaseTitle(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class Retryable(RootModel[bool]):
    root: bool


class RevocationStatus(RootModel[str]):
    root: str


class ScheduleDate(RootModel[constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')]):
    root: constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')


class Scheduled(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Optional[datetime] = None
    start: Optional[datetime] = None


class ScheduledPublicationRights(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    publication_rights: Optional[List[PublicationRights]] = None


class ScheduledTime(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Optional[datetime] = None
    start: Optional[datetime] = None


class SeriesOf(RootModel[PidReference]):
    root: PidReference


class ServiceReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    result_type: str
    sid: str


class Short(RootModel[str]):
    root: str


class Sid(RootModel[constr(pattern=r'[a-z0-9A-Z_\.\-]+')]):
    root: constr(pattern=r'[a-z0-9A-Z_\.\-]+')


class Size(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    units: Optional[str] = None


class SnippetUrl(RootModel[str]):
    root: str


class SortDirection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    is_default: str
    name: str
    value: str


class SourceAsset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dimensions: Optional[Dimensions] = None
    focus_point: Optional[FocusPoint] = None
    mime_type: Optional[str] = None
    size: Optional[Size] = None
    uri: Optional[str] = None


class SourceMedia(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class StartTime(RootModel[datetime]):
    root: datetime


class Status(RootModel[str]):
    root: str


class Synopses(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    long: Optional[Long] = None
    medium: Optional[Medium] = None
    short: Optional[Short] = None


class Title(RootModel[str]):
    root: str


class TrackNumber(RootModel[constr(min_length=1, max_length=8)]):
    root: constr(min_length=1, max_length=8)


class TrackSide(RootModel[constr(min_length=1, max_length=8)]):
    root: constr(min_length=1, max_length=8)


class TxTime(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    credits_showing: Optional[datetime] = None
    end: Optional[datetime] = None
    start: Optional[datetime] = None


class TypeModel(RootModel[str]):
    model_config = ConfigDict(
        extra='forbid',
    )
    root: str


class TypeItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None


class Types1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: List[TypeItem1] = Field(..., min_length=1)


class TypeItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None
    types: Types1


class Types(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: List[TypeItem] = Field(..., min_length=1)


class TypesWithId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    types: Types


class UpdatedTime(RootModel[datetime]):
    root: datetime


class Uri(RootModel[str]):
    root: str


class Url(RootModel[str]):
    root: str


class UrlKey(RootModel[str]):
    root: str


class Availability3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability_end: Optional[datetime] = None
    availability_start: Optional[datetime] = None
    available_media_sets: AvailableMediaSets
    status: Optional[str] = None


class Availability2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability: Availability3
    availability_end: Optional[datetime] = None
    availability_start: Optional[datetime] = None
    available_media_sets: AvailableMediaSets
    status: Optional[str] = None


class VersionAvailability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability: Availability2


class Availability4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_availability: List[VersionAvailability] = Field(..., min_length=1)


class Type2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Optional[List[str]] = None


class VersionOf(RootModel[PidReference]):
    root: PidReference


class VersionTypeItem5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None


class VersionTypes3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_type: List[VersionTypeItem5] = Field(..., min_length=1)


class VersionTypeItem4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = None
    version_types: VersionTypes3


class VersionTypes2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_type: List[VersionTypeItem4] = Field(..., min_length=1)


class VersionTypesWithId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_types: VersionTypes2


class Warning(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    short_description: Optional[str] = None
    warning_code: Optional[str] = None


class WarningItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    short_description: Optional[str] = None
    warning_code: Optional[str] = None


class WarningItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    short_description: Optional[str] = None
    warning: Optional[List[WarningItem1]] = None
    warning_code: Optional[str] = None


class WarningItems(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    warning: Optional[List[WarningItem]] = None


class WarningText(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    length: Optional[str] = None


class WarningTextItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    length: Optional[str] = None


class WarningTextItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    length: Optional[str] = None
    warning_text: Optional[List[WarningTextItem1]] = None


class WarningTexts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    warning_text: Optional[List[WarningTextItem]] = None


class Warnings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    warning: Optional[List[Warning]] = None
    warning_text: Optional[List[WarningText]] = None


class WindowOf(RootModel[PidReference]):
    root: PidReference


class XqueryVersion(Enum):
    field_1_0_ml = '1.0-ml'
    field_0_9_ml = '0.9-ml'
    field_1_0 = '1.0'
    XSLT = 'XSLT'


class Sort1(Enum):
    scheduled_start = 'scheduled_start'


class SortDirection1(Enum):
    ascending = 'ascending'
    descending = 'descending'


class AvailabilityEnum(Enum):
    available = 'available'


class TerritoryEnum(Enum):
    uk = 'uk'
    nonuk = 'nonuk'
    world = 'world'


class Availability6(RootModel[List[AvailabilityEnum]]):
    root: List[AvailabilityEnum]


class DescendantsOf(
    RootModel[List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]]
):
    root: List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]


class MediaSet1(RootModel[List[str]]):
    root: List[str]


class Territory(RootModel[List[TerritoryEnum]]):
    root: List[TerritoryEnum]


class Sort3(Enum):
    start_date = 'start_date'


class MixinEnum(Enum):
    titles = 'titles'


class Mixin1(RootModel[List[MixinEnum]]):
    root: List[MixinEnum]


class Authority(RootModel[List[str]]):
    root: List[str]


class Format1(RootModel[List[str]]):
    root: List[str]


class Genre1(RootModel[List[str]]):
    root: List[str]


class Id1(RootModel[List[str]]):
    root: List[str]


class Item1(
    RootModel[List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]]
):
    root: List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]


class Pid1(
    RootModel[List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]]
):
    root: List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]


class ServiceMasterBrand(RootModel[List[str]]):
    root: List[str]


class Sid1(RootModel[List[str]]):
    root: List[str]


class Version4(
    RootModel[List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]]
):
    root: List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]


class Sort5(Enum):
    pid = 'pid'


class SortDirection5(Enum):
    descending = 'descending'


class MixinEnum2(Enum):
    alternate_images = 'alternate_images'
    group_for = 'group_for'
    images = 'images'
    related_links = 'related_links'


class GroupTypeEnum(Enum):
    collection = 'collection'
    franchise = 'franchise'
    gallery = 'gallery'
    season = 'season'


class Embargoed1(Enum):
    include = 'include'
    exclude = 'exclude'
    only = 'only'


class Mixin2(RootModel[List[MixinEnum2]]):
    root: List[MixinEnum2]


class GroupType(RootModel[List[GroupTypeEnum]]):
    root: List[GroupTypeEnum]


class PartnerId(
    RootModel[List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]]
):
    root: List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]


class PartnerPid(
    RootModel[List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]]
):
    root: List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]


class Sort7(Enum):
    group_position = 'group_position'
    pid = 'pid'


class SortDirection7(Enum):
    ascending = 'ascending'
    descending = 'descending'


class ImageTypeEnum(Enum):
    standard = 'standard'
    podcast = 'podcast'
    store = 'store'
    portrait = 'portrait'
    letterbox = 'letterbox'


class ImageType(RootModel[List[ImageTypeEnum]]):
    root: List[ImageTypeEnum]


class Sort9(Enum):
    pid = 'pid'


class SortDirection9(Enum):
    descending = 'descending'


class MixinEnum4(Enum):
    contributions = 'contributions'
    images = 'images'
    offset = 'offset'
    play_event = 'play_event'


class ItemTypeEnum(Enum):
    chapter = 'chapter'
    highlight = 'highlight'
    music = 'music'
    speech = 'speech'
    other = 'other'


class Mixin3(RootModel[List[MixinEnum4]]):
    root: List[MixinEnum4]


class ItemType(RootModel[List[ItemTypeEnum]]):
    root: List[ItemTypeEnum]


class Sort11(Enum):
    mid = 'mid'


class SortDirection11(Enum):
    ascending = 'ascending'


class MixinEnum6(Enum):
    images = 'images'


class Mixin4(RootModel[List[MixinEnum6]]):
    root: List[MixinEnum6]


class Mid1(RootModel[List[str]]):
    root: List[str]


class HasExternalIdEnum(Enum):
    true = 'true'
    false = 'false'


class HasExternalId(RootModel[List[HasExternalIdEnum]]):
    root: List[HasExternalIdEnum]


class Sort13(Enum):
    group_position = 'group_position'
    pid = 'pid'
    position = 'position'
    promotion = 'promotion'
    release_date = 'release_date'
    relevance = 'relevance'
    scheduled_start = 'scheduled_start'
    strict_title = 'strict_title'
    title = 'title'
    tree = 'tree'


class SortDirection13(Enum):
    ascending = 'ascending'
    descending = 'descending'


class MixinEnum8(Enum):
    alternate_images = 'alternate_images'
    ancestor_titles = 'ancestor_titles'
    availability = 'availability'
    available_simulcasts = 'available_simulcasts'
    available_versions = 'available_versions'
    available_webcasts = 'available_webcasts'
    contributions = 'contributions'
    duration = 'duration'
    genre_groupings = 'genre_groupings'
    genre_groups = 'genre_groups'
    images = 'images'
    is_embeddable = 'is_embeddable'
    previous_next = 'previous_next'
    programme_type = 'programme_type'
    related_links = 'related_links'
    titles = 'titles'
    versions_availability = 'versions_availability'


class AudioDescribedEnum(Enum):
    true = 'true'
    false = 'false'


class AvailabilityEnum2(Enum):
    available = 'available'
    pending = 'pending'


class AvailabilityEntityTypeEnum(Enum):
    episode = 'episode'
    clip = 'clip'


class AvailabilityTypeEnum(Enum):
    ondemand = 'ondemand'
    webcast = 'webcast'
    simulcast = 'simulcast'


class DurationEnum(Enum):
    short = 'short'
    medium = 'medium'
    long = 'long'


class EntityTypeEnum(Enum):
    brand = 'brand'
    series = 'series'
    episode = 'episode'
    clip = 'clip'


class MediaTypeEnum(Enum):
    audio = 'audio'
    audio_video = 'audio_video'


class PaymentTypeEnum(Enum):
    free = 'free'
    bbcstore = 'bbcstore'
    uscansvod = 'uscansvod'


class SignedEnum(Enum):
    exclusive = 'exclusive'
    inclusive = 'inclusive'
    exclude = 'exclude'


class TleoEnum(Enum):
    true = 'true'
    false = 'false'


class Mixin5(RootModel[List[MixinEnum8]]):
    root: List[MixinEnum8]


class AudioDescribed(RootModel[List[AudioDescribedEnum]]):
    root: List[AudioDescribedEnum]


class Availability7(RootModel[List[AvailabilityEnum2]]):
    root: List[AvailabilityEnum2]


class AvailabilityEntityType(RootModel[List[AvailabilityEntityTypeEnum]]):
    root: List[AvailabilityEntityTypeEnum]


class AvailabilityType1(RootModel[List[AvailabilityTypeEnum]]):
    root: List[AvailabilityTypeEnum]


class ChildrenOf(
    RootModel[List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]]
):
    root: List[constr(pattern=r'^([0-9,a-d,f-h,j-n,p-t,v-z]){8,}$', min_length=8)]


class Duration(RootModel[List[DurationEnum]]):
    root: List[DurationEnum]


class EntityType(RootModel[List[EntityTypeEnum]]):
    root: List[EntityTypeEnum]


class InitialLetterStrict(RootModel[List[constr(min_length=1, max_length=1)]]):
    root: List[constr(min_length=1, max_length=1)]


class MasterBrand3(RootModel[List[str]]):
    root: List[str]


class MediaType1(RootModel[List[MediaTypeEnum]]):
    root: List[MediaTypeEnum]


class PaymentType(RootModel[List[PaymentTypeEnum]]):
    root: List[PaymentTypeEnum]


class Signed(RootModel[List[SignedEnum]]):
    root: List[SignedEnum]


class Tleo(RootModel[List[TleoEnum]]):
    root: List[TleoEnum]


class MixinEnum10(Enum):
    related_links = 'related_links'


class StatusEnum(Enum):
    current = 'current'


class Mixin6(RootModel[List[MixinEnum10]]):
    root: List[MixinEnum10]


class PromotedBy1(RootModel[List[str]]):
    root: List[str]


class PromotedFor1(RootModel[List[str]]):
    root: List[str]


class Status1(RootModel[List[StatusEnum]]):
    root: List[StatusEnum]


class Sort15(Enum):
    start_date = 'start_date'


class MixinEnum12(Enum):
    ancestor_titles = 'ancestor_titles'
    images = 'images'
    titles = 'titles'


class Mixin7(RootModel[List[MixinEnum12]]):
    root: List[MixinEnum12]


class IdType(RootModel[List[str]]):
    root: List[str]


class ServiceTypeEnum(Enum):
    Interactive = 'Interactive'
    Local_Radio = 'Local Radio'
    Master_Brand_Only = 'Master Brand Only'
    National_Radio = 'National Radio'
    On_Demand = 'On Demand'
    Regional_Radio = 'Regional Radio'
    Simulcast = 'Simulcast'
    TV = 'TV'
    Web_Only = 'Web Only'
    Webcast = 'Webcast'


class ServiceType(RootModel[List[ServiceTypeEnum]]):
    root: List[ServiceTypeEnum]


class AvailabilityEnum4(Enum):
    available = 'available'


class Availability8(RootModel[List[AvailabilityEnum4]]):
    root: List[AvailabilityEnum4]


class PaymentType1(RootModel[List[PaymentTypeEnum]]):
    root: List[PaymentTypeEnum]


class AccurateProgrammeTime(RootModel[DateRange]):
    root: DateRange


class Brand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pid: Pid
    title: Optional[Title] = None


class Episode1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    containers_title: Optional[ContainersTitle] = None
    pid: Pid
    presentation_title: Optional[PresentationTitle] = None
    title: Optional[Title] = None


class Series(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pid: Pid
    title: Optional[Title] = None


class Episode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    brand: Optional[Brand] = None
    containers_title: Optional[ContainersTitle] = None
    episode: Optional[Episode1] = None
    pid: Pid
    presentation_title: Optional[PresentationTitle] = None
    series: Optional[List[Series]] = Field(None, max_length=5)
    title: Optional[Title] = None


class AncestorTitles(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    brand: Optional[Brand] = None
    episode: Optional[Episode] = None
    series: Optional[List[Series]] = Field(None, max_length=5)


class Episode3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    containers_title: Optional[ContainersTitle] = None
    pid: Pid
    presentation_title: Optional[PresentationTitle] = None
    title: Optional[Title] = None


class Episode2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    brand: Optional[Brand] = None
    containers_title: Optional[ContainersTitle] = None
    episode: Optional[Episode3] = None
    pid: Pid
    presentation_title: Optional[PresentationTitle] = None
    series: Optional[List[Series]] = Field(None, max_length=5)
    title: Optional[Title] = None


class AncestorsTitles(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    brand: Optional[Brand] = None
    episode: Optional[Episode2] = None
    series: Optional[List[Series]] = Field(None, max_length=5)


class AvailabilityItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    version_types: VersionTypes1


class VersionTypeItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability: Optional[List[AvailabilityItem1]] = None
    end: Optional[datetime] = None
    id: Optional[str] = None
    start: Optional[datetime] = None


class VersionTypeItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Optional[datetime] = None
    id: Optional[str] = None
    start: Optional[datetime] = None
    version_type: List[VersionTypeItem1] = Field(..., min_length=1)


class VersionTypes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_type: List[VersionTypeItem] = Field(..., min_length=1)


class AvailabilityItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    version_types: VersionTypes


class AvailabilityMixin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability: Optional[List[AvailabilityItem]] = None


class AvailabilityOf(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    pid: Pid
    result_type: str
    type: Optional[str] = None


class AvailabilityItem2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accurate_end: Optional[datetime] = None
    accurate_start: Optional[datetime] = None
    available_versions_media_sets: AvailableVersionsMediaSets
    media_availability_end: Optional[datetime] = None
    media_availability_start: Optional[datetime] = None
    payment_type: Optional[str] = None
    scheduled_end: Optional[datetime] = None
    scheduled_start: Optional[datetime] = None
    status: Optional[str] = None
    type: Optional[str] = None


class Availabilities1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability: List[AvailabilityItem2] = Field(..., min_length=1)
    type: Optional[str] = None


class Availabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availabilities: Availabilities1
    availability: List[AvailabilityItem2] = Field(..., min_length=1)
    type: Optional[str] = None


class AvailableMixins(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availabilities: Availabilities


class BroadcastTime(DateRange):
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None


class BroadcastOf(RootModel[PidReference]):
    root: PidReference


class Broadcaster(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    result_type: str
    sid: Sid


class ClipOf(RootModel[PidReference]):
    root: PidReference


class Context(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cascades_to_descendants: Optional[bool] = None
    href: Optional[str] = None
    pid: Pid
    result_type: str


class Contributor1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contributions_mixin_contributor_name: Optional[
        ContributionsMixinContributorName
    ] = None
    href: Optional[str] = None
    type: Optional[TypeModel] = None


class Contributor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contributions_mixin_contributor_name: Optional[
        ContributionsMixinContributorName
    ] = None
    contributor: Contributor1
    href: Optional[str] = None
    type: Optional[TypeModel] = None


class ContributionsMixinContributor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contributor: Contributor


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    datum: Optional[Datum] = None


class DeprecatedReferenceElement(ReferenceAttributes, DeprecationAttributes):
    pass


class EpisodeOf(RootModel[PidReference]):
    root: PidReference


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    data: Data
    error_name: ErrorName = Field(..., alias='error-name')
    expr: Expr
    format_string: FormatString = Field(..., alias='format-string')
    message: Message
    retryable: Retryable
    xquery_version: XqueryVersion = Field(..., alias='xquery-version')


class Errors(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Optional[Error] = None


class GenreGroupingsType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    genre_group: Optional[List[GenreGroup]] = None


class GenreGroupsType(DeprecatedReferenceElement):
    genre_group: Optional[List[GenreGroup]] = None


class GenreGroupings(RootModel[GenreGroupingsType]):
    root: GenreGroupingsType


class GenreGroups(RootModel[GenreGroupsType]):
    root: GenreGroupsType


class Warnings1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    warning_items: Optional[WarningItems] = None
    warning_texts: Optional[WarningTexts] = None


class WarningsModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    warning_items: Optional[WarningItems] = None
    warning_texts: Optional[WarningTexts] = None
    warnings: Optional[Warnings1] = None


class GuidanceWarnings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    warnings: Optional[WarningsModel] = None


class Image2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pid: Optional[Pid] = None
    template_url: str


class Image1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image: Image2
    pid: Optional[Pid] = None
    template_url: str


class ImageLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image: Union[DeprecationAttributes, Image1]


class CompetitionWarning1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    pid: Pid


class MasterBrand2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    mid: Mid
    result_type: str


class MasterBrand1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    master_brand: MasterBrand2
    mid: Mid
    result_type: str


class MasterBrandLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    master_brand: MasterBrand1


class MediaProfileGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = Field(None, alias='#text')
    context: Optional[str] = None
    pid: Optional[Pid] = None
    platform: Optional[str] = None
    territory: Optional[str] = None
    transport: Optional[str] = None


class MediaProfileGroups(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_profile_group: Optional[List[MediaProfileGroup]] = None


class Mixin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    affected_by: Optional[List[AffectedBy]] = None
    dependency_on: Optional[List[DependencyOn]] = None
    depends_on: Optional[str] = None
    deprecated: Optional[bool] = None
    deprecated_since: Optional[constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')] = None
    guaranteed_until: Optional[constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')] = None
    href: Optional[str] = None
    name: str
    prohibits: Optional[List[Prohibits]] = None
    release_status: Optional[ReleaseStatusType] = None
    replaced_by: Optional[str] = None
    title: str


class OffsetIn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str
    offset: Optional[int] = None
    position: Optional[float] = None
    programme: Pid
    version: Pid


class Offsets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    offset_in: Optional[List[OffsetIn]] = None


class Option(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: Optional[str] = None
    release_status: Optional[ReleaseStatusType] = None
    title: str
    value: str


class Version1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None
    href: str
    pid: Pid


class Version(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None
    href: str
    pid: Pid
    version: Optional[Version1] = None


class OriginalVersionDuration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: Optional[Version] = None


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    next: Optional[Next] = None
    previous: Optional[Previous] = None


class Partner(RootModel[Pid]):
    root: Pid


class PlayEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    offset: Optional[int] = None
    pid: Pid
    played_in_links: Optional[List[PlayedInLinks]] = None
    position: Optional[float] = None
    synopses: Optional[Synopses] = None
    title: Optional[str] = None


class PlayEvents(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    play_event: Optional[List[PlayEvent]] = None


class PublishedTime(RootModel[BroadcastTime]):
    root: BroadcastTime


class Reference(ReferenceAttributes):
    href_deprecated: Optional[bool] = None
    result_type_deprecated: Optional[bool] = None


class RelatedLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability: Optional[Availability1] = None
    is_external: Optional[IsExternal] = None
    pid: Pid
    position: Optional[Position] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    type: Optional[TypeModel] = None
    uri: Optional[Uri] = None


class RelatedLinks(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    related_link: Optional[List[RelatedLink]] = None


class Service(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date_range: Optional[DateRange] = None
    description: Optional[Description] = None
    identifiers: Optional[Identifiers] = None
    ids: Optional[Ids] = None
    is_concrete: Optional[IsConcrete] = None
    is_downloadable: Optional[IsDownloadable] = None
    is_streamable: Optional[IsStreamable] = None
    master_brand_link: Optional[MasterBrandLink] = None
    media_type: Optional[MediaType] = None
    name: Optional[NameModel] = None
    partner: Partner
    region: Optional[Region] = None
    sid: Sid
    type: Optional[TypeModel] = None
    updated_time: Optional[UpdatedTime] = None


class Sort(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deprecated: Optional[bool] = None
    deprecated_since: Optional[constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')] = None
    guaranteed_until: Optional[constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')] = None
    is_default: Optional[str] = None
    name: str
    release_status: Optional[ReleaseStatusType] = None
    replaced_by: Optional[str] = None
    sort_direction: Optional[List[SortDirection]] = None
    title: str


class UnstableMixins(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mixin: Optional[List[Mixin]] = None


class UnstableSorts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sort: Optional[List[Sort]] = None


class VersionItem3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availabilities: Optional[List[Availability4]] = None
    competition_warning: Optional[str] = None
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None
    guidance_warnings: Optional[GuidanceWarnings] = None
    pid: Optional[Pid] = None
    types: List[Type2] = Field(..., min_length=1)


class VersionItem2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availabilities: Optional[List[Availability4]] = None
    competition_warning: Optional[str] = None
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None
    guidance_warnings: Optional[GuidanceWarnings] = None
    pid: Optional[Pid] = None
    types: List[Type2] = Field(..., min_length=1)
    version: Optional[List[VersionItem3]] = None


class VersionAvailabilityMixin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: Optional[List[VersionItem2]] = None


class Version3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aspect_ratio: Optional[str] = None
    competition_warning: Optional[CompetitionWarning] = None
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None
    identifiers: Optional[Identifiers] = None
    ids: Optional[Ids] = None
    pid: Pid
    types_with_id: Optional[TypesWithId] = None
    updated_time: UpdatedTime
    version_of: Optional[VersionOf] = None
    version_types_with_id: Optional[VersionTypesWithId] = None
    warnings: Optional[Warnings] = None


class Version2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aspect_ratio: Optional[str] = None
    competition_warning: Optional[CompetitionWarning] = None
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None
    identifiers: Optional[Identifiers] = None
    ids: Optional[Ids] = None
    pid: Pid
    types_with_id: Optional[TypesWithId] = None
    updated_time: UpdatedTime
    version: Version3
    version_of: Optional[VersionOf] = None
    version_types_with_id: Optional[VersionTypesWithId] = None
    warnings: Optional[Warnings] = None


class VersionGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: Version2


class Versions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: int
    version_availability_mixin: VersionAvailabilityMixin


class Window(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accurate_programme_time: Optional[AccurateProgrammeTime] = None
    ancestor_titles: Optional[AncestorTitles] = None
    ancestors_titles: Optional[AncestorsTitles] = None
    identifiers: Optional[Identifiers] = None
    ids: Optional[Ids] = None
    image_link: Optional[ImageLink] = None
    images_mixin: Optional[ImagesMixin] = None
    media_availability_time: Optional[MediaAvailabilityTime] = None
    partner: Partner
    pid: Pid
    scheduled_publication_rights: Optional[ScheduledPublicationRights] = None
    scheduled_time: Optional[ScheduledTime] = None
    service: Optional[ServiceReference] = None
    updated_time: Optional[UpdatedTime] = None
    window_of: Optional[List[WindowOf]] = None


class AccurateTime(RootModel[BroadcastTime]):
    root: BroadcastTime


class Ancestors(RootModel[Reference]):
    root: Reference


class AvailabilityDebug(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability_of: PidReference
    media_profile_groups: Optional[MediaProfileGroups] = None
    service: Optional[ServiceReference] = None
    territory: Optional[str] = None


class VersionItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available_mixins: Optional[AvailableMixins] = None
    competition_warning: Optional[bool] = None
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None
    guidance_warnings: Optional[GuidanceWarnings] = None
    pid: Optional[Pid] = None
    types: List[Type] = Field(..., min_length=1)


class VersionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available_mixins: Optional[AvailableMixins] = None
    competition_warning: Optional[bool] = None
    duration: Optional[
        constr(
            pattern=r'^(-)?P(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)W)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?$'
        )
    ] = None
    guidance_warnings: Optional[GuidanceWarnings] = None
    pid: Optional[Pid] = None
    types: List[Type] = Field(..., min_length=1)
    version: Optional[List[VersionItem1]] = None


class AvailableVersionsElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: Optional[List[VersionItem]] = None


class AvailableWebcasts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: int
    available_versions_element: AvailableVersionsElement


class Broadcast(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ancestor_titles: Optional[AncestorTitles] = None
    ancestors_titles: Optional[AncestorsTitles] = None
    broadcast_of: Optional[List[BroadcastOf]] = None
    identifiers: Optional[Identifiers] = None
    ids: Optional[Ids] = None
    image_link: Optional[ImageLink] = None
    images_mixin: Optional[ImagesMixin] = None
    is_audio_described: Optional[IsAudioDescribed] = None
    is_blanked: Optional[IsBlanked] = None
    is_critical: Optional[IsCritical] = None
    is_repeat: Optional[IsRepeat] = None
    is_simulcast: Optional[IsSimulcast] = None
    partner: Partner
    pid: Pid
    published_time: Optional[PublishedTime] = None
    service: Optional[ServiceReference] = None
    tx_time: Optional[TxTime] = None
    updated_time: Optional[UpdatedTime] = None


class Contribution1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    character_name: Optional[str] = None
    contributions_mixin_contributor: Optional[ContributionsMixinContributor] = None
    credit_role: Optional[CreditRole] = None


class Contribution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    character_name: Optional[str] = None
    contribution: Contribution1
    contributions_mixin_contributor: Optional[ContributionsMixinContributor] = None
    credit_role: Optional[CreditRole] = None


class ContributionsMixinContribution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contribution: Contribution


class Contributor2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contributor_name: Optional[ContributorName] = None
    contributor_to: Optional[List[ContributorTo]] = None
    disambiguation: Optional[Disambiguation] = None
    href: Optional[str] = None
    identifiers: Optional[Identifiers] = None
    ids: Optional[Ids] = None
    partner: Partner
    pid: Pid
    type: Optional[TypeModel] = None


class Filter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: Optional[str] = None
    depends_on: Optional[str] = None
    deprecated: Optional[bool] = None
    deprecated_since: Optional[constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')] = None
    guaranteed_until: Optional[constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$')] = None
    max_value: Optional[int] = None
    min_value: Optional[int] = None
    multiple_values: Optional[bool] = None
    name: str
    option: Optional[List[Option]] = None
    prefer: Optional[str] = None
    prohibits: Optional[List[Prohibits]] = None
    release_status: Optional[ReleaseStatusType] = None
    replaced_by: Optional[str] = None
    required: Optional[bool] = None
    title: str
    type: str


class Franchises(RootModel[Reference]):
    root: Reference


class GroupBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alternate_images_mixin: Optional[AlternateImagesMixin] = None
    embargoed: Embargoed
    for_programmes: Optional[ForProgrammes] = None
    identifiers: Optional[Identifiers] = None
    ids: Optional[Ids] = None
    images_mixin: Optional[ImagesMixin] = None
    master_brand_link: Optional[MasterBrandLink] = None
    partner: Partner
    pid: Pid
    related_links: Optional[RelatedLinks] = None
    scheduled: Optional[Scheduled] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    updated_time: UpdatedTime
    url_key: Optional[UrlKey] = None


class Image(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    author: Optional[str] = None
    embargoed: Embargoed
    identifiers: Optional[Identifiers] = None
    partner: Partner
    pid: Pid
    shoot_date: Optional[datetime] = None
    source_asset: Optional[SourceAsset] = None
    synopses: Optional[Synopses] = None
    template_url: Optional[str] = None
    title: Optional[Title] = None
    type: Optional[str] = None


class ItemOf(RootModel[Reference]):
    root: Reference


class ItemsFor(RootModel[Reference]):
    root: Reference


class MasterBrand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    colour: Optional[str] = None
    competition_warning: Optional[CompetitionWarning1] = None
    ident: Optional[str] = None
    identifiers: Optional[Identifiers] = None
    image_link: Optional[ImageLink] = None
    images_mixin: Optional[ImagesMixin] = None
    master_brand_date_range: Optional[MasterBrandDateRange] = None
    mid: Mid
    name: Optional[NameModel] = None
    partner: Partner
    position: Optional[Position] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    url_key: Optional[str] = None


class Mixins(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mixin: Optional[List[Mixin]] = None
    unstable_mixins: Optional[UnstableMixins] = None


class PreviousNext1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    next: Optional[Reference] = None
    previous: Optional[Reference] = None


class PreviousNext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    next: Optional[Reference] = None
    previous: Optional[Reference] = None
    previous_next: PreviousNext1


class PreviousNextMixin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    previous_next: PreviousNext


class Promotion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context: Optional[Context] = None
    end_time: Optional[EndTime] = None
    identifiers: Optional[Identifiers] = None
    partner: Partner
    pid: Pid
    priority: Optional[Priority] = None
    promoted_by: Optional[PromotedBy] = None
    promoted_for: Optional[PromotedFor] = None
    promotion_of: Optional[PromotionOf] = None
    related_links: Optional[RelatedLinks] = None
    start_time: Optional[StartTime] = None
    status: Optional[Status] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    updated_time: UpdatedTime
    uri: Optional[Uri] = None
    url: Optional[Url] = None


class Season(RootModel[GroupBody]):
    root: GroupBody


class Sorts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sort: Optional[List[Sort]] = None
    unstable_sorts: Optional[UnstableSorts] = None


class UnstableFilters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filter: Optional[List[Filter]] = None


class Availability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accurate_programme_time: Optional[AccurateProgrammeTime] = None
    actual_start: Optional[ActualStart] = None
    availability_debug: Optional[AvailabilityDebug] = Field(
        None, alias='availability-debug'
    )
    availability_of: Optional[List[AvailabilityOf]] = None
    availability_type: AvailabilityType
    media_availability_time: Optional[MediaAvailabilityTime] = None
    media_set: Optional[List[MediaSet]] = None
    revocation_status: Optional[RevocationStatus] = None
    scheduled_time: Optional[ScheduledTime] = None
    status: Status


class AvailableSimulcasts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: int
    available_versions_element: AvailableVersionsElement


class AvailableVersions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: int
    available_versions_element: AvailableVersionsElement


class Collection(RootModel[GroupBody]):
    root: GroupBody


class Contributions1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contributions_mixin_contribution: Optional[List[ContributionsMixinContribution]] = (
        None
    )
    href: Optional[str] = None


class Contributions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contributions: Contributions1
    contributions_mixin_contribution: Optional[List[ContributionsMixinContribution]] = (
        None
    )
    href: Optional[str] = None


class ContributionsMixin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contributions: Contributions


class Filters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filter: Optional[List[Filter]] = None
    unstable_filters: Optional[UnstableFilters] = None


class Franchise(RootModel[GroupBody]):
    root: GroupBody


class Gallery(RootModel[GroupBody]):
    root: GroupBody


class Item(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    catalogue_number: Optional[CatalogueNumber] = None
    contributions_mixin: Optional[ContributionsMixin] = None
    duration: Optional[float] = None
    identifiers: Optional[Identifiers] = None
    ids: Optional[Ids] = None
    images_mixin: Optional[ImagesMixin] = None
    item_of: Optional[ItemOf] = None
    music_code: Optional[MusicCode] = None
    offsets: Optional[Offsets] = None
    partner: Partner
    pid: Pid
    play_events: Optional[PlayEvents] = None
    publisher: Optional[Publisher] = None
    record_label: Optional[RecordLabel] = None
    recording_date: Optional[RecordingDate] = None
    release_title: Optional[ReleaseTitle] = None
    snippet_url: Optional[SnippetUrl] = None
    source_media: Optional[SourceMedia] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    track_number: Optional[TrackNumber] = None
    track_side: Optional[TrackSide] = None
    type: Optional[str] = None
    updated_time: Optional[UpdatedTime] = None


class Music(RootModel[Item]):
    root: Item


class Other(RootModel[Item]):
    root: Item


class SeriesModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alternate_images_mixin: Optional[AlternateImagesMixin] = None
    ancestor_titles: Optional[AncestorTitles] = None
    ancestors: Optional[Ancestors] = None
    ancestors_titles: Optional[AncestorsTitles] = None
    availability_mixin: Optional[AvailabilityMixin] = None
    contributions_mixin: Optional[ContributionsMixin] = None
    embargoed: Embargoed
    expected_child_count: Optional[ExpectedChildCount] = None
    genre_groupings: Optional[GenreGroupings] = None
    identifiers: Optional[Identifiers] = None
    image_link: Optional[ImageLink] = None
    images_mixin: Optional[ImagesMixin] = None
    is_embeddable: Optional[IsEmbeddable] = None
    items_for: Optional[ItemsFor] = None
    master_brand_link: Optional[MasterBrandLink] = None
    partner: Partner
    pid: Pid
    previous_next_mixin: Optional[PreviousNextMixin] = None
    programme_formats: Optional[ProgrammeFormats] = None
    programme_type: Optional[ProgrammeType] = None
    related_links: Optional[RelatedLinks] = None
    release_date_group: Optional[ReleaseDateGroup] = None
    series_of: Optional[SeriesOf] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    updated_time: UpdatedTime
    uri: Optional[Uri] = None


class Speech(RootModel[Item]):
    root: Item


class VersionsMixin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available_simulcasts: Optional[AvailableSimulcasts] = None
    available_versions: Optional[AvailableVersions] = None
    available_webcasts: Optional[AvailableWebcasts] = None
    versions: Optional[List[Versions]] = None


class Brand4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alternate_images_mixin: Optional[AlternateImagesMixin] = None
    availability_mixin: Optional[AvailabilityMixin] = None
    contributions_mixin: Optional[ContributionsMixin] = None
    embargoed: Embargoed
    expected_child_count: Optional[ExpectedChildCount] = None
    franchises: Optional[Franchises] = None
    genre_groupings: Optional[GenreGroupings] = None
    identifiers: Optional[Identifiers] = None
    image_link: Optional[ImageLink] = None
    images_mixin: Optional[ImagesMixin] = None
    is_embeddable: Optional[IsEmbeddable] = None
    items_for: Optional[ItemsFor] = None
    master_brand_link: Optional[MasterBrandLink] = None
    partner: Partner
    pid: Pid
    previous_next_mixin: Optional[PreviousNextMixin] = None
    programme_formats: Optional[ProgrammeFormats] = None
    programme_type: Optional[ProgrammeType] = None
    related_links: Optional[RelatedLinks] = None
    release_date_group: Optional[ReleaseDateGroup] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    updated_time: UpdatedTime
    uri: Optional[Uri] = None


class Chapter(RootModel[Item]):
    root: Item


class Clip(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    advertising_allowed: AdvertisingAllowed
    alternate_images_mixin: Optional[AlternateImagesMixin] = None
    ancestor_titles: Optional[AncestorTitles] = None
    ancestors: Optional[Ancestors] = None
    ancestors_titles: Optional[AncestorsTitles] = None
    availability_mixin: Optional[AvailabilityMixin] = None
    caption: Optional[Caption] = None
    clip_of: Optional[ClipOf] = None
    contributions_mixin: Optional[ContributionsMixin] = None
    embargoed: Embargoed
    genre_groupings: Optional[GenreGroupings] = None
    genre_groups: Optional[GenreGroups] = None
    identifiers: Optional[Identifiers] = None
    image_link: Optional[ImageLink] = None
    images_mixin: Optional[ImagesMixin] = None
    is_embeddable: Optional[IsEmbeddable] = None
    items_for: Optional[ItemsFor] = None
    master_brand_link: Optional[MasterBrandLink] = None
    media_type: Optional[MediaType] = None
    original_version_duration: Optional[OriginalVersionDuration] = None
    partner: Partner
    pid: Pid
    previous_next_mixin: Optional[PreviousNextMixin] = None
    programme_formats: Optional[ProgrammeFormats] = None
    related_links: Optional[RelatedLinks] = None
    release_date_group: Optional[ReleaseDateGroup] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    updated_time: UpdatedTime
    uri: Optional[Uri] = None
    versions_mixin: Optional[VersionsMixin] = None


class Episode4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    advertising_allowed: AdvertisingAllowed
    alternate_images_mixin: Optional[AlternateImagesMixin] = None
    ancestor_titles: Optional[AncestorTitles] = None
    ancestors: Optional[Ancestors] = None
    ancestors_titles: Optional[AncestorsTitles] = None
    availability_mixin: Optional[AvailabilityMixin] = None
    contributions_mixin: Optional[ContributionsMixin] = None
    embargoed: Embargoed
    episode_of: Optional[EpisodeOf] = None
    genre_groupings: Optional[GenreGroupings] = None
    genre_groups: Optional[GenreGroups] = None
    has_guidance: Optional[HasGuidance] = None
    identifiers: Optional[Identifiers] = None
    image_link: Optional[ImageLink] = None
    images_mixin: Optional[ImagesMixin] = None
    is_embeddable: Optional[IsEmbeddable] = None
    is_stacked: Optional[IsStacked] = None
    items_for: Optional[ItemsFor] = None
    master_brand_link: Optional[MasterBrandLink] = None
    media_type: Optional[MediaType] = None
    original_version_duration: Optional[OriginalVersionDuration] = None
    partner: Partner
    pid: Pid
    presentation_title: Optional[PresentationTitle] = None
    previous_next_mixin: Optional[PreviousNextMixin] = None
    programme_formats: Optional[ProgrammeFormats] = None
    programme_type: Optional[ProgrammeType] = None
    related_links: Optional[RelatedLinks] = None
    release_date_group: Optional[ReleaseDateGroup] = None
    synopses: Optional[Synopses] = None
    title: Optional[Title] = None
    updated_time: UpdatedTime
    uri: Optional[Uri] = None
    versions_mixin: Optional[VersionsMixin] = None


class Feed(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deprecations: Optional[Deprecations] = None
    filters: Optional[Filters] = None
    href: str
    mixins: Optional[Mixins] = None
    name: str
    rel: str
    release_status: Optional[ReleaseStatusType] = None
    sorts: Optional[Sorts] = None
    title: str


class Feeds(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deployment_root: Optional[str] = None
    deprecations: Optional[Deprecations] = None
    feed: Optional[List[Feed]] = None


class Highlight(RootModel[Item]):
    root: Item


class Results(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availability: Optional[Availability] = None
    brand: Optional[Brand4] = None
    broadcast: Optional[Broadcast] = None
    chapter: Optional[Chapter] = None
    clip: Optional[Clip] = None
    collection: Optional[Collection] = None
    contributor: Optional[Contributor2] = None
    episode: Optional[Episode4] = None
    franchise: Optional[Franchise] = None
    gallery: Optional[Gallery] = None
    highlight: Optional[Highlight] = None
    image: Optional[Image] = None
    master_brand: Optional[MasterBrand] = None
    more_than: Optional[int] = None
    music: Optional[Music] = None
    other: Optional[Other] = None
    page: int
    page_size: int
    promotion: Optional[Promotion] = None
    season: Optional[Season] = None
    series: Optional[SeriesModel] = None
    service: Optional[Service] = None
    speech: Optional[Speech] = None
    total: Optional[int] = None
    version_group: Optional[VersionGroup] = None
    window: Optional[Window] = None


class Nitro(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    deprecations: Optional[Deprecations] = None
    filters: Optional[Filters] = None
    mixins: Optional[Mixins] = None
    pagination: Optional[Pagination] = None
    results: Optional[Results] = None
    sorts: Optional[Sorts] = None
